version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    depends_on:
      - postgres
      - mongodb
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./app:/app
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: brian
      POSTGRES_PASSWORD: Bandit2015
      POSTGRES_DB: user_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
volumes:
  postgres-data:
  mongodb-data:
